Repository mdaugherity/PythonGuide, pull requests merged in 2024-12, with the labels that each got.

#7 Scipy stats phoebe's brainrot
  ScipyStatsNormal.ipynb
Labels: documentation

#6 Polyfit Guide
  PolyFit_.ipynb
Labels: enhancement

#5 Pandas csv files
  CSV_pandas_guide.ipynb
  Pandasexample2.csv
  example.csv
Labels: enhancement

#9 Solve_BVP
  Solve_BVP.ipynb
Labels: help wanted
